### ISSUE TITLE
ESPTelloCLI Compile errors

### ISSUE THREAD

**Issue by jsolderitsch** [touchgadget/ESPTelloCLI#2]
Please see attached Screen shot
```
/Users/jjs/Documents/Arduino/libraries/ESPTelloCLI-main/examples/ESPTelloCLI/ESPTelloCLI.ino: In function 'void WiFiEvent(system_event_id_t)':
ESPTelloCLI:36:12: error: 'ARDUINO_EVENT_WIFI_STA_GOT_IP' was not declared in this scope
       case ARDUINO_EVENT_WIFI_STA_GOT_IP:
            ^
ESPTelloCLI:48:12: error: 'ARDUINO_EVENT_WIFI_STA_DISCONNECTED' was not declared in this scope
       case ARDUINO_EVENT_WIFI_STA_DISCONNECTED:
            ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/jjs/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
'ARDUINO_EVENT_WIFI_STA_GOT_IP' was not declared in this scope
```
I have a generic ESP32-WROOM-32 Dev board. Running Arduino 1.8.19.
My ESP 32 support comes from this additional board manager URL inclusion.
```
https://dl.espressif.com/dl/package_esp32_index.json
```
![Screen Shot 2022-06-14 at 7 56 00 PM](https://user-images.githubusercontent.com/23091236/173708886-70811988-be2b-4359-9005-6fb410009dd5.png)

I am running on a Mac.

**Comment by touchgadget** [comment]
The most recent version of the ESP32 Arduino package is 2.0.3. I use the following URL.

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

**Comment by jsolderitsch** [comment]
I changed the board setting with this URL and no change. Is there anything else I need to do to refresh the package to make it be 2.0.3? I haven't done a lot of Arduino programming so I might be missing something.

**Comment by jsolderitsch** [comment]
I did find this link:
[Updating](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)

I followed this and I do not get compile errors now.

**Comment by jsolderitsch** [comment]
And I can report that the sketch works. I will close the issue now
